version: '3'
services:

    ganache:
        image: trufflesuite/ganache-cli:latest
        # UID:GID => id -u, id -g
        user: "1000:1000"
        ports:
            - "8545:8545"
        volumes:
            # mount a data location from the host into the container - read-write
            - "${PWD}/teststack/ganache/.data:/ganache:rw"
        command:
            # https://github.com/trufflesuite/ganache-cli#using-ganache-cli
            - "--accounts"
            - "15"
            - "--defaultBalanceEther"
            - "1000"
            - "--deterministic"
            - "--mnemonic"
            - "myth like bonus scare over problem client lizard pioneer submit female collect"
            - "--gasLimit"
            - "0xfffffffffff"
            - "--gasPrice"
            - "1"
            - "--port"
            - "8545"
            - "--networkId"
            - "5777"
            - "--db"
            - "/ganache"

    crossbar:
        depends_on:
          - ganache
        image: crossbario/crossbarfx:latest
        # UID:GID => id -u, id -g
        user: "1000:1000"
        network_mode: host
        #ports:
        #    - "8080:8080"
        volumes:
            - "${PWD}/teststack/crossbar:/node"
